import javax.sql.DataSource;
import java.util.HashMap;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SqlService {
    private DataSource ds;
    private HashMap<String, String> queryMap;

    SqlService(String sqlFilesPath, DataSource ds) {
        this.ds = ds;
        System.out.println("Reading queries from --> " + sqlFilesPath);
        this.queryMap = new QueryMapBuilder(sqlFilesPath).getQueryMap();
    }


}


class Main {


    public static void main(String[] args) {
        QueryMapBuilder queryMapBuilder = new QueryMapBuilder("/home/shubhang/opensource/sql-service/sql");
        queryMapBuilder.getQueryMap();
    }
}
