import javax.sql.DataSource;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SqlService {
    private DataSource ds;
    private String sqlFilesPath;


    SqlService(String sqlFilesPath) {
        this.ds = ds;
        this.sqlFilesPath = sqlFilesPath;
    }


}


class Main {


    public static void main(String[] args) {
        QueryMapBuilder queryMapBuilder = new QueryMapBuilder("/home/shubhang/opensource/sql-service/sql");
        queryMapBuilder.getQueryMap();
    }
}
