/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SqlServiceTest {
    @Test public void testSomeLibraryMethod() {
//        SqlService classUnderTest = new SqlService();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
