/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.h2.jdbcx.JdbcDataSource;
import org.junit.Before;
import org.junit.Test;

import javax.sql.DataSource;

import static com.google.common.base.Predicates.instanceOf;
import static org.junit.Assert.assertThat;
import static org.springframework.util.Assert.isInstanceOf;

public class SqlServiceTest {

    DataSource ds;

    @Before
    public void setup() {
        ds = new JdbcDataSource();
        ((JdbcDataSource) ds).setURL("jdbc:h2:˜/test");
        ((JdbcDataSource) ds).setUser("sa");
        ((JdbcDataSource) ds).setPassword("sa");
    }

    @Test
    public void shouldReturnSqlServiceObject() {
        SqlService sqlService = new SqlService("/home/shubhang/opensource/sql-service/src/test/resource", ds);
    }
}
